server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k7c204.p.ssafy.io:3306/comssa?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&amp
    username: root
    password: comssaC204!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/comssa_app?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: thekey1919


#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: comssa
  data:
    mongodb:
      uri: mongodb+srv://S07P31C204:comssaC204!@ssafy.ngivl.mongodb.net/S07P31C204?authSource=admin


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 615676148746-ltjgjc06koe78oo6vcn9b2rd1du21cos.apps.googleusercontent.com
            clientSecret: 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
#            redirect-uri: "http://localhost:8080/oauth2/callback/google"
            redirect-uri: "https://k7c204.p.ssafy.io/api/oauth2/callback/google"
            scope:
              - email
              - profile
          naver:
            clientId: W7Jq18MlVPJQ0gdf_0oF
            clientSecret: nJ8y0WqCJp
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/oauth2/callback/naver"
#            redirect-uri: "https://k7c204.p.ssafy.io/api/oauth2/callback/naver"

            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
          kakao:
            clientId: 9801ad08f8d5a556fa5aa7062582c327
            clientSecret: hv153n2mnh5nqFw6xjsQB5mRoKcxlJL5
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/oauth2/callback/kakao"
#            redirect-uri: "https://k7c204.p.ssafy.io/api/oauth2/callback/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true


# cors 설정
#cors:
#  allowed-origins: 'http://localhost:3000', 'http://localhost:8080'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600

h2:
  console:
    enabled: true

app:
  cors:
    allowedOrigins: http://localhost:3000, http://localhost:8080, http://k7c204.p.ssafy.io:3000, http://k7c204.p.ssafy.io:8080, https://k7c204.p.ssafy.io
  auth:
    # JWT를 암호화 하기 위한 암호화 키
    tokenSecret: 'c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK'
    accessTokenExpirationMsec: 1800000
    refreshTokenExpiryMsec: 604800000

  oauth2:
    # OAuth2 공급자로 성공적으로 인증 한 후 사용자에 대한 인증 토큰을 생성하고 토큰을
    # 프론트 엔드 클라이언트가 /oauth2/authorize 요청에서 지정한 redirectUri 입니다.
    # 쿠키는 모바일 클라이언트에서 잘 작동하지 않기 때문에 사용하지 않습니다
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
#      - http://k7c204.p.ssafy.io/oauth2/redirect

#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    supported-submit-methods: "get" "put" "post" "delete" "options" "head" "patch" "trace"
#
